### ISSUE TITLE
Error occured while proccesing the data

### ISSUE THREAD

**Issue by vertuk** [KevinCFechtel/FluxNews#23]
Can't start syncing my feeds from my Miniflux instance on my arm64 SBC at home, an error occures: "Error occured while proccesing the data"

API URL: http://192.168.0.3:7001/v1/
API Key: NhQtw9WgfUCIE3RP5yzTWoEvOZhrt1UwPeI0gm2Tq38=
Miniflux version: 2.0.51

Miniflux API
API Endpoint = http://192.168.0.3/v1/ (didn't work with localhost too)
Username = admin
Password = Your account password

Logs:
[3012202315.log](https://github.com/KevinCFechtel/FluxNews/files/13797537/3012202315.log)

FluxNews version: 1.3.3

I am using Docker-compose stack of miniflux/miniflux:latest [sha256:583afb597db848] and postgres:15 [sha256:1aa6a6a531189f2] in the backend. Works fine in the browser.

**Comment by KevinCFechtel** [comment]
Hi, it looks like the feed icon is too big to be stored (or retrieved) in the database.
In the other issue I am currently optimizing the processing of large amounts of data, one part of this is to change the processing of the feed icons.
This change will also solve your problem. 
As soon as I have created a new release, I will let you know here.

**Comment by KevinCFechtel** [comment]
The new relase has just been released, the storage of the feed icons has been revised there and the problem should be fixed.

**Comment by vertuk** [comment]
Just got 1.3.4 from F-Droid, works fine now.
