### ISSUE TITLE
Side menu feed title overlap

### ISSUE THREAD

**Issue by dm1tz** [KevinCFechtel/FluxNews#24]
If the feed title in sidemenu is long it overlaps the feed item count. 
![photo1703950410](https://github.com/KevinCFechtel/FluxNews/assets/82608185/3a4b8406-312c-48a9-9fee-cf00a38ef681)

**Comment by KevinCFechtel** [comment]
Thanks for the hint, the overflow is adjusted in some places in the next release.
<img width="275" alt="Category_title_overflow" src="https://github.com/KevinCFechtel/FluxNews/assets/26933592/2369f96f-7191-43d5-8825-53483bfdb524">
<img width="272" alt="Feed_title_overflow" src="https://github.com/KevinCFechtel/FluxNews/assets/26933592/42f7f596-985f-4934-975f-0bfc32c5dd1c">
<img width="355" alt="News_card_overflow" src="https://github.com/KevinCFechtel/FluxNews/assets/26933592/a1776df4-daa7-48a4-bb55-63c2bc2d59bb">

**Comment by dm1tz** [comment]
> Thanks for the hint, the overflow is adjusted in some places in the next release. <img alt="Category_title_overflow" width="275" src="https://private-user-images.githubusercontent.com/26933592/293475456-2369f96f-7191-43d5-8825-53483bfdb524.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5NzQwOTAsIm5iZiI6MTcwMzk3Mzc5MCwicGF0aCI6Ii8yNjkzMzU5Mi8yOTM0NzU0NTYtMjM2OWY5NmYtNzE5MS00M2Q1LTg4MjUtNTM0ODNiZmRiNTI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDIyMDMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0NDdjMDhkNGIyOTc3NzY4M2QwMGUyMDgxODIzNDM1NWZiZDBmOGY1YzIzOWMzYjcxODg2OGRiOGU3ZjNjOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tlDAxSF3ZEgtgZZSYoW09oRuuxhMZMFjQ84w8j0hBP0"> <img alt="Feed_title_overflow" width="272" src="https://private-user-images.githubusercontent.com/26933592/293475457-42f7f596-985f-4934-975f-0bfc32c5dd1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5NzQwOTAsIm5iZiI6MTcwMzk3Mzc5MCwicGF0aCI6Ii8yNjkzMzU5Mi8yOTM0NzU0NTctNDJmN2Y1OTYtOTg1Zi00OTM0LTk3NWYtMGJmYzMyYzVkZDFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDIyMDMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0NDQ1MWI4MGY0N2I0MDA5MmUzYzk2YmQ0NGVjYWQ5OWRjYjExZGIwZDQyM2VkYWJkYzA3MDI5Y2Y5NmNiNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-ydurR8rM6pfRW-t1idf8pTSxFkNsUN7UyiW22mmXoI"> <img alt="News_card_overflow" width="355" src="https://private-user-images.githubusercontent.com/26933592/293475459-a1776df4-daa7-48a4-bb55-63c2bc2d59bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5NzQwOTAsIm5iZiI6MTcwMzk3Mzc5MCwicGF0aCI6Ii8yNjkzMzU5Mi8yOTM0NzU0NTktYTE3NzZkZjQtZGFhNy00OGE0LWJiNTUtNjNjMmJjMmQ1OWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDIyMDMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwNWU5Njk4ODZhNDIyMWUwMTczNTY1MDI3ZmMxY2FjZTlmYTZmNjY0YjI0YjQzMDI3MDQ2MjY0MzBmZWE0N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.96STgNcGpdhY5m33xaGsfTOEfvwtGpm7MFjTEBGnY7U">

Thanks.

**Comment by KevinCFechtel** [comment]
The new relase has just been released, the problem with the overflow has been fixed there.
