### ISSUE TITLE
API URL Setting Errors Out for Certain URLs

### ISSUE THREAD

**Issue by Abraxos** [KevinCFechtel/FluxNews#26]
Hello,

I am having an issue connecting to my personal Miniflux instance. It is hosted at `miniflux.kovalev.systems` however, I cannot configure this as the URL because whenever I put in the full URL (`https://miniflux.kovalev.systems/v1/`) I am informed that I need to "Enter a valid Miniflux URL with trailing slash" so I am unable to even save this configuration element.

What's really strange, however, is that I am able to save other, invalid URLs such as `https://miniflux.kovalev.system/v1/` (note the difference between `.system` and `.systems`) just fine even though nothing is hosted at such a URL. It seems that removing just one letter from the hostname is enough because `https://miniflux.kvalev.systems/v1/` also allows me to save without issue. Sadly, since these are not real domains, I am not actually able to log in.

This feels like a bug. I would love to use Flux News with my setup though, so please let me know if there is any other information I can provide for you. Sadly, the logs don't appear to have anything about this. Even after activating Debug Logging:

```
{FluxNews}  {readConfigValues}  {Starting read config values}  {07 January 2024 12:22:46 AM}  {INFO}
{FluxNews}  {readConfigValues}  {Finished read config values}  {07 January 2024 12:22:46 AM}  {INFO}
{FluxNews}  {readConfig}  {Starting read config}  {07 January 2024 12:22:46 AM}  {INFO}
{FluxNews}  {readConfig}  {Finished read config}  {07 January 2024 12:22:46 AM}  {INFO}
{FluxNews}  {initializeDB}  {Starting initializeDB}  {07 January 2024 12:22:46 AM}  {INFO}
{FluxNews}  {initializeDB}  {Finished initializeDB}  {07 January 2024 12:22:46 AM}  {INFO}
{FlutterLogsPlugin}  {exportPLogs}  {PLogs Path: FluxNewsLogs/FluxNewsLogs/Exported/07012024_002926_AM_all_[2].zip}  {07 January 2024 12:29:26 AM}  {INFO}
{FluxNews}  {checkMinifluxCredentials}  {Starting checking miniflux credentials}  {07 January 2024 12:32:53 AM}  {INFO}
```

**Comment by KevinCFechtel** [comment]
Hello, 
the problem was that my URL check had not yet been adapted to the new TLDs. 
I have adjusted the check and now new TLDs that are longer than the previous maximum of 6 characters should also work.
Sorry for that.
Regards,
Kevin

**Comment by KevinCFechtel** [comment]
The new release should be available in f-droid within the next 5 days.

**Comment by Abraxos** [comment]
You're awesome! Thank you!
