### ISSUE TITLE
Button mark as read 

### ISSUE THREAD

**Issue by toketin** [KevinCFechtel/FluxNews#30]
Hi, I guess that a simple button to set the feeds as readed may be useful.

Thanks!

**Comment by KevinCFechtel** [comment]
Would you think that there is a button in the upper right 3 dot menu that does the following:
Mark all messages of this feed as read when a feed is currently selected.
When a category is currently selected, mark all messages from all feeds in the category as read.
When selecting all messages, mark all messages (of all feeds) as read.
I would implement this soon. 
If you have any other ideas, please let me know.

**Comment by KevinCFechtel** [comment]
I have added the button with the described functionality.
The new release should be displayed for updating in the next few days.
