### ISSUE TITLE
Can't configure Miniflux server URL

### ISSUE THREAD

**Issue by gioxx** [KevinCFechtel/FluxNews#31]
As already described and reported in the bug https://github.com/KevinCFechtel/FluxNews/issues/26, I have the same problem with a self-hosted Miniflux instance on a domain with tld ".cc".
I would like to try the application but - simply - I can't.

**Comment by KevinCFechtel** [comment]
Could you tell me the structure of the URL?
For example: https://xxx.yyy.cc/v1/
Normally a domain with .cc should not be a problem.

**Comment by gioxx** [comment]
Sure: Miniflux.domain.cc

Il mar 26 mar 2024, 15:03 Kevin Fechtel ***@***.***> ha
scritto:

**Comment by KevinCFechtel** [comment]
Is this the exact URL that is also displayed in the "API Endpoint" item in Miniflux under the API Keys section?
Is the /v1/ part missing?

**Comment by gioxx** [comment]
You are absolutely right. I was not including v1 because a different application did not need it and connected directly with the API token and the main URL of Miniflux. I tried again by specifying it and confirm that the application connects correctly.
Again, thank you for your patience and support.

**Comment by rubiojr** [comment]
I came here for the same reason. Somehow, I missread the README and thought the `/v1/` should NOT be added, when it states the opposite...

**Comment by rubiojr** [comment]
The app is superb, BTW, congrats. And thanks!

**Comment by KevinCFechtel** [comment]
My idea was actually that the URL from the miniflux API key page could simply be copied and pasted. 
However, if it leads to confusion, I will include an automatic addition to the /v1/ part in the next release, then both the base URL and the one from the settings page can be used.
And many thanks for the feedback!

**Comment by gioxx** [comment]
> My idea was actually that the URL from the miniflux API key page could simply be copied and pasted.

Just to make the point and allow you to understand better: I have the Miniflux installation that I reach via Cloudflare tunnel. The URL shown in my case is localhost but obviously that is not the case, and that I can point to the https address of my installation via Cloudflare tunnel. Copying and pasting directly into your application would not be correct at all :-)

BTW: thanks again for your support and application :-)

**Comment by KevinCFechtel** [comment]
With the release 1.3.7 I have simplified the input of the URL.
You can now also enter the base URL.
The part with the api version `/v1/` is then automatically added to the URL.
This also eliminates the misleading message that the URL is not correct if the `/v1/` part of the URL is missing.
Missing `/` are also added to the end of the URL.
