### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [KevinCFechtel/FluxNews#33]
https://gitlab.com/fdroid/fdroiddata/-/jobs/6514484681

It seems you need to update the flutter submodule. Thanks!

**Comment by KevinCFechtel** [comment]
Should be fixed with the new published release tag.

**Comment by linsui** [comment]
You just need to fork fdroiddata and push your change. :)

**Comment by linsui** [comment]
Thanks!
