### ISSUE TITLE
Feature request: Specify how many entries to sync, don't block instances with more than 10K unread

### ISSUE THREAD

**Issue by ozls** [KevinCFechtel/FluxNews#35]
Hello! I'm interested in using this app, but unfortunately it seems that since I have more than 10K unread entries on my instance it just refuses to load anything. However, I don't really care about loading all my unread entries in the app, it indeed seems like it would be a bad idea. Would it not be better to choose how many entries to sync, instead of trying to sync all of them by default? If that feature makes it in the app I would love to give it a try!

**Comment by KevinCFechtel** [comment]
Hi, would you expect the sorting of the local item list (newest first or oldest first) to be applied to the sync if the number of items is limited? 
So that only the newest or oldest 1000 items are synced, depending on the setting?

**Comment by ozls** [comment]
Yes that is what I would expect.

**Comment by KevinCFechtel** [comment]
OK, then I will implement the feature in the next few days and give feedback here when the new release is published.

**Comment by KevinCFechtel** [comment]
With the new release, it is now possible to limit the number of messages to be synchronized or searched.
The error message for a sync with more than 10,000 items also indicates now, that the number of messages can be limited. 
The release should be available for download in the next few days.
