### ISSUE TITLE
would this app compatible with Android 10

### ISSUE THREAD

**Issue by include-nan** [KevinCFechtel/FluxNews#42]
the phone I use is still Android 10, but the app required 11 at least, I wonder know is there possilbe to compile with a lower target.

**Comment by KevinCFechtel** [comment]
I'll go through the dependencies and see if I can go down to Android 10. 
That will take a little while, though, because unfortunately I have a lot to do at the moment.

**Comment by include-nan** [comment]
It's so nice of you, waiting for your good news

**Comment by KevinCFechtel** [comment]
Hello, it looks good, with a min sdk version of 29 (android 10) the app can be compiled without errors.
Have you tried downloading the app via the playstore or via f-droid?

**Comment by include-nan** [comment]
wow, It's sooooo nice of you!
But I still hava some problem that I tried to build the lastest version with github actions for hours, 
finnaly failed... because I hava no experence of android developping

**Comment by KevinCFechtel** [comment]
You do not need to create the app yourself, I will try to provide an update via Google Play and F-Droid in the course of the week, which includes compatibility for Android 10.

**Comment by KevinCFechtel** [comment]
small update, unfortunately the release cannot currently be published on fdroid because the following problem still exists:
https://gitlab.com/fdroid/fdroiddata/-/issues/3282

**Comment by KevinCFechtel** [comment]
The update with support for android 10 has now been released and should be available for download in the Play Store and f-droid Store in the next few days.
Sorry for the delay!
