### ISSUE TITLE
Feature request: Option to truncate body text

### ISSUE THREAD

**Issue by snauth** [KevinCFechtel/FluxNews#44]
Love the simplicity of this app and feel hesitant to request a feature. But the option to truncate body text would make Miniflux' "Fetch original content" more useful which otherwise can lead to a lot of scrolling. Why would I want to fetch the fulltext and then truncate it again? My motivation is mainly esthetic since "Fetch original content" also fetches images that then give context to the entries.

**Comment by KevinCFechtel** [comment]
I currently have the following logic for displaying the article text:
If the plaintext exists and is greater than 50 characters before the first linebreak, then display it, otherwise search for the first html paragraph (<p> tag) and display its content.
This solution worked for my feeds, but it is not a general solution. 
Do you have any ideas how this could be improved, I would be happy to receive new ideas 😊

**Comment by snauth** [comment]
Hi, not sure if we understand each other. If I tell miniflux to fetch the original content (in the feed preferences) it (often) pulls  in an image which is then displayed in FluxNews list. This is what I want. But it also pulls in a (sometimes very) long wall of plain text without linebreak which makes scrolling cumbersome. I would like to truncate this text.

**Comment by KevinCFechtel** [comment]
So you would like to have an option in the settings that the text of the news is cut off after 100, 200, 500 or 1000 characters (after the last word) and then, if necessary, with "..." as suffix at the end shown in the app?
That's a good idea, I'll try to implement it next week, but the default setting is to display the entire text, with the option to limit it accordingly if you want.

**Comment by KevinCFechtel** [comment]
I have also considered offering an option for the character limit, whether this limit applies to:
all messages
or only to messages from feeds where the scraper (fetch original content) is activated 
or only to messages from feeds with an activated scraper and without an active scraper order rewrite rule.
This means that the option should be quite individually usable.

**Comment by snauth** [comment]
Thanks so much! I look very much forward to the next release!
