### ISSUE TITLE
Error while communicating with the miniflux server

### ISSUE THREAD

**Issue by mujupug** [KevinCFechtel/FluxNews#49]
Upgrading from 1.4.1 to any of the releases later throws an error at me. I assume the bit of the logs that matters is **net::ERR_CLEARTEXT_NOT_PERMITTED**.

I've cleared the app data, reinstalled, rebooted etc. Even created a new API key despite things working before an upgrade and none of that seems to matter. 

`{FluxNews}  {readConfigValues}  {Starting read config values}  {23 June 2024 07:04:15 PM}  {INFO}
{FluxNews}  {initializeDB}  {Starting initializeDB}  {23 June 2024 07:04:15 PM}  {INFO}
{FluxNews}  {initializeDB}  {Finished initializeDB}  {23 June 2024 07:04:15 PM}  {INFO}
{FluxNews}  {initializeDB}  {Starting creating DB}  {23 June 2024 07:04:15 PM}  {INFO}
{FluxNews}  {initializeDB}  {Finished creating DB}  {23 June 2024 07:04:15 PM}  {INFO}
{FluxNews}  {readConfigValues}  {Finished read config values}  {23 June 2024 07:04:16 PM}  {INFO}
{FluxNews}  {initializeDB}  {Starting initializeDB}  {23 June 2024 07:04:16 PM}  {INFO}
{FluxNews}  {initializeDB}  {Finished initializeDB}  {23 June 2024 07:04:16 PM}  {INFO}
{FluxNews}  {readConfig}  {Starting read config}  {23 June 2024 07:04:16 PM}  {INFO}
{FluxNews}  {readConfig}  {Finished read config}  {23 June 2024 07:04:16 PM}  {INFO}
{FluxNews}  {readConfigValues}  {Starting read config values}  {23 June 2024 07:04:16 PM}  {INFO}
{FluxNews}  {readConfigValues}  {Finished read config values}  {23 June 2024 07:04:16 PM}  {INFO}
{FluxNews}  {readConfig}  {Starting read config}  {23 June 2024 07:04:16 PM}  {INFO}
{FluxNews}  {readConfig}  {Finished read config}  {23 June 2024 07:04:16 PM}  {INFO}
{FluxNews}  {initializeDB}  {Starting initializeDB}  {23 June 2024 07:04:16 PM}  {INFO}
{FluxNews}  {initializeDB}  {Finished initializeDB}  {23 June 2024 07:04:16 PM}  {INFO}
{FluxNews}  {syncNews}  {Start syncing with miniflux server.}  {23 June 2024 07:07:04 PM}  {INFO}
{FluxNews}  {checkMinifluxCredentials}  {Starting checking miniflux credentials}  {23 June 2024 07:07:04 PM}  {INFO}
{FluxNews}  {authCheck}  {Caught an error in authCheck function! : ClientException: Cronet exception: org.chromium.net.impl.NetworkExceptionImpl: Exception in CronetUrlRequest: net::ERR_CLEARTEXT_NOT_PERMITTED, ErrorCode=11, InternalErrorCode=-29, Retryable=false, uri=http://ipaddress/v1/me}  {23 June 2024 07:07:04 PM}  {ERROR}
{FluxNews}  {syncNews}  {Syncing with miniflux server executed in 0:00:00.054631}  {23 June 2024 07:07:04 PM}  {INFO}
{FluxNews}  {syncNews}  {Finished syncing with miniflux server.}  {23 June 2024 07:07:04 PM}  {INFO}
{FluxNews}  {syncNews}  {Start syncing with miniflux server.}  {23 June 2024 07:07:05 PM}  {INFO}
{FluxNews}  {checkMinifluxCredentials}  {Starting checking miniflux credentials}  {23 June 2024 07:07:05 PM}  {INFO}
{FluxNews}  {authCheck}  {Caught an error in authCheck function! : ClientException: Cronet exception: org.chromium.net.impl.NetworkExceptionImpl: Exception in CronetUrlRequest: net::ERR_CLEARTEXT_NOT_PERMITTED, ErrorCode=11, InternalErrorCode=-29, Retryable=false, uri=http://ipaddress/v1/me}  {23 June 2024 07:07:05 PM}  {ERROR}
{FluxNews}  {syncNews}  {Syncing with miniflux server executed in 0:00:00.011588}  {23 June 2024 07:07:05 PM}  {INFO}
{FluxNews}  {syncNews}  {Finished syncing with miniflux server.}  {23 June 2024 07:07:05 PM}  {INFO}
{FluxNews}  {readConfigValues}  {Starting read config values}  {23 June 2024 07:07:11 PM}  {INFO}
{FluxNews}  {readConfigValues}  {Finished read config values}  {23 June 2024 07:07:11 PM}  {INFO}
{FluxNews}  {readConfig}  {Starting read config}  {23 June 2024 07:07:11 PM}  {INFO}
{FluxNews}  {readConfig}  {Finished read config}  {23 June 2024 07:07:12 PM}  {INFO}
{FluxNews}  {initializeDB}  {Starting initializeDB}  {23 June 2024 07:07:12 PM}  {INFO}
{FluxNews}  {initializeDB}  {Finished initializeDB}  {23 June 2024 07:07:12 PM}  {INFO}
{FluxNews}  {checkMinifluxCredentials}  {Starting checking miniflux credentials}  {23 June 2024 07:07:21 PM}  {INFO}
{FluxNews}  {syncNews}  {Start syncing with miniflux server.}  {23 June 2024 07:07:33 PM}  {INFO}
{FluxNews}  {checkMinifluxCredentials}  {Starting checking miniflux credentials}  {23 June 2024 07:07:33 PM}  {INFO}
{FluxNews}  {authCheck}  {Caught an error in authCheck function! : ClientException: Cronet exception: org.chromium.net.impl.NetworkExceptionImpl: Exception in CronetUrlRequest: net::ERR_CLEARTEXT_NOT_PERMITTED, ErrorCode=11, InternalErrorCode=-29, Retryable=false, uri=http://ipaddress/v1/me}  {23 June 2024 07:07:33 PM}  {ERROR}
{FluxNews}  {syncNews}  {Syncing with miniflux server executed in 0:00:00.009050}  {23 June 2024 07:07:33 PM}  {INFO}
{FluxNews}  {syncNews}  {Finished syncing with miniflux server.}  {23 June 2024 07:07:33 PM}  {INFO}
{FluxNews}  {readConfigValues}  {Starting read config values}  {23 June 2024 07:07:36 PM}  {INFO}
{FluxNews}  {readConfigValues}  {Finished read config values}  {23 June 2024 07:07:36 PM}  {INFO}
{FluxNews}  {readConfig}  {Starting read config}  {23 June 2024 07:07:36 PM}  {INFO}
{FluxNews}  {readConfig}  {Finished read config}  {23 June 2024 07:07:36 PM}  {INFO}
{FluxNews}  {initializeDB}  {Starting initializeDB}  {23 June 2024 07:07:36 PM}  {INFO}
{FluxNews}  {initializeDB}  {Finished initializeDB}  {23 June 2024 07:07:36 PM}  {INFO}`

**Comment by KevinCFechtel** [comment]
Hello, is the IP address a private or a public one? 
I suspect that the cronet http client handles plaintext connections differently than the native one. 
I'll try to debug it tomorrow and create a hotfix release.

**Comment by akumar-xyz** [comment]
First of all, thanks for all the work on the app!

I noticed a similar issue. Installed an older version (1.4.2) from F-Droid and the issue is gone. I have a local DNS setup pointing to my miniflux.

Logs if it helps:
```
{FluxNews}  {readConfigValues}  {Starting read config values}  {25 June 2024 12:47:42 AM}  {INFO}
{FluxNews}  {initializeDB}  {Starting initializeDB}  {25 June 2024 12:47:42 AM}  {INFO}
{FluxNews}  {initializeDB}  {Finished initializeDB}  {25 June 2024 12:47:42 AM}  {INFO}
{FluxNews}  {initializeDB}  {Starting creating DB}  {25 June 2024 12:47:42 AM}  {INFO}
{FluxNews}  {initializeDB}  {Finished creating DB}  {25 June 2024 12:47:42 AM}  {INFO}
{FluxNews}  {readConfigValues}  {Finished read config values}  {25 June 2024 12:47:44 AM}  {INFO}
{FluxNews}  {initializeDB}  {Starting initializeDB}  {25 June 2024 12:47:44 AM}  {INFO}
{FluxNews}  {initializeDB}  {Finished initializeDB}  {25 June 2024 12:47:44 AM}  {INFO}
{FluxNews}  {readConfig}  {Starting read config}  {25 June 2024 12:47:44 AM}  {INFO}
{FluxNews}  {readConfig}  {Finished read config}  {25 June 2024 12:47:44 AM}  {INFO}
{FluxNews}  {readConfigValues}  {Starting read config values}  {25 June 2024 12:47:44 AM}  {INFO}
{FluxNews}  {readConfigValues}  {Finished read config values}  {25 June 2024 12:47:44 AM}  {INFO}
{FluxNews}  {readConfig}  {Starting read config}  {25 June 2024 12:47:44 AM}  {INFO}
{FluxNews}  {readConfig}  {Finished read config}  {25 June 2024 12:47:44 AM}  {INFO}
{FluxNews}  {initializeDB}  {Starting initializeDB}  {25 June 2024 12:47:44 AM}  {INFO}
{FluxNews}  {initializeDB}  {Finished initializeDB}  {25 June 2024 12:47:44 AM}  {INFO}
{FluxNews}  {syncNews}  {Start syncing with miniflux server.}  {25 June 2024 12:48:53 AM}  {INFO}
{FluxNews}  {authCheck}  {Caught an error in authCheck function! : ClientException: Cronet exception: org.chromium.net.impl.NetworkExceptionImpl: Exception in CronetUrlRequest: net::ERR_CLEARTEXT_NOT_PERMITTED, ErrorCode=11, InternalErrorCode=-29, Retryable=false, uri=http://miniflux.server.home/v1/me}  {25 June 2024 12:48:53 AM}  {ERROR}
{FluxNews}  {syncNews}  {Finished syncing with miniflux server.}  {25 June 2024 12:48:53 AM}  {INFO}
{FluxNews}  {readConfigValues}  {Starting read config values}  {25 June 2024 12:48:57 AM}  {INFO}
{FluxNews}  {readConfigValues}  {Finished read config values}  {25 June 2024 12:48:57 AM}  {INFO}
{FluxNews}  {readConfig}  {Starting read config}  {25 June 2024 12:48:57 AM}  {INFO}
{FluxNews}  {readConfig}  {Finished read config}  {25 June 2024 12:48:57 AM}  {INFO}
{FluxNews}  {initializeDB}  {Starting initializeDB}  {25 June 2024 12:48:57 AM}  {INFO}
{FluxNews}  {initializeDB}  {Finished initializeDB}  {25 June 2024 12:48:57 AM}  {INFO}
{FluxNews}  {deleteLocalNewsCache}  {Starting deleting the local news cache}  {25 June 2024 12:49:05 AM}  {INFO}
{FluxNews}  {deleteLocalNewsCache}  {Finished deleting the local news cache}  {25 June 2024 12:49:05 AM}  {INFO}
{FluxNews}  {checkMinifluxCredentials}  {Starting checking miniflux credentials}  {25 June 2024 12:49:09 AM}  {INFO}
{FlutterLogsPlugin}  {exportPLogs}  {PLogs Path: FluxNewsLogs/FluxNewsLogs/Exported/25062024_004913_AM_all_[1].zip}  {25 June 2024 12:49:13 AM}  {INFO}
{FluxNews}  {checkMinifluxCredentials}  {Starting checking miniflux credentials}  {25 June 2024 12:49:32 AM}  {INFO}
```

**Comment by mujupug** [comment]
> ?

It's a private IP. Not sure why I snipped a 192.168 thing out. 

As @akumar-xyz mentioned above too thanks a lot for the work on this. It's a wonderful app.

**Comment by KevinCFechtel** [comment]
I have just created a new release which should now fix the bug.
The release has already been submitted for publication in the Play Store and should also be published in the f-droid store in the next 5 days. 
Sorry for the inconvenience!

**Comment by mujupug** [comment]
Thank you for that and don't be sorry. It's been a day since the problem was even brought to your attention and then fixed. That's amazing. <3

**Comment by mujupug** [comment]
Installed from the play store and can confirm issue is resolved.
