### ISSUE TITLE
Opening news items

### ISSUE THREAD

**Issue by Bujiraso** [KevinCFechtel/FluxNews#61]
Hello. Beautiful app -- thanks for publishing it.

I am signed upto [Hacker News' best of](https://hnrss.org/best) and I can't figure out how to open the item to tap the second link in Flux News.

For this type of feed item, I need to be able to open the item itself and tap on links inside of it. If you have a look, you'll see each entry has the article of interest and then the comments link. It's very formulaic that way, but I constantly have to leave Flux News every time one of these pops up. As of my current version (1.6.2), it seems like the only thing that can be opened is the `<link>` contents, which means I can't get to the HN comments. Is it possible to do what I'm looking for in the current revision?

It might be easiest on the impl side to point out that I'd be perfectly happy with a FluxNews where I can somehow tap, swipe, or menu on the news item and it will open the full feed entry from my self-hosted miniflux instead of the <link> target. Either in-app or not, then I can access the links like I mostly do now, but without having to (1) menu out (2) open browser (3) go to my miniflux (4) nav into this feed (5) find the article in question (6) tap.

Thanks for any help!

**Comment by KevinCFechtel** [comment]
Hi, thanks for the info, I understand the problem. 
Would it be a solution to be able to set per feed whether the link of the news item should be opened directly, or whether the news item should be opened in the Miniflux interface in the InApp browser instead?
I am currently working on a version 1.7 which now allows settings per feed and this would be a useful feature.
This would mean that you could navigate back and forth between the two links via the Miniflux interface using the In App Browser.
If you can't do this per feed in general, but for each news item individually, then it could become a configurable slide action. 
I will probably implement both options in the new version, then you should have maximum flexibility.

**Comment by Bujiraso** [comment]
Per feed could definitely work. Most of my feeds, I never really "noticed" this -- the content is the <link>, or even just a preview. So that sounds great, thank you! Per news item individually as a swipe action seems more niche, but not in any way a "bad" idea.

Looking forward to it, happy to test beta candidates if they pop-up.

**Comment by KevinCFechtel** [comment]
I have just released a new release that includes the feature. 
It is now possible to make several settings per feed, including the option to open the entry directly in the miniflux Web gui. 
The same can also be selected as a swipe action if you only want to use this occasionally.
If there are still problems, simply open a new ticket.
